### ISSUE TITLE
Day 32 Lab - Missing Technical Requirements

### ISSUE THREAD

**Issue by elaewin** [thegrimheep/CoreDataHotel#12]
You're still missing the following requirements:

* `DatePickerViewController` should have both `startDate` and `endDate` date pickers. All views should get their proper layout from `Auto Layout` and **not** by assigning their frame.  
  * When selecting dates, users should not be allowed to select dates in the past for the start date.  
  * Users should also not be able to book an end date before a start date.

**Comment by thegrimheep** [comment]
This is now completed
